"""fix fk schema qualification and add cascade on role_permissions, user_roles

Revision ID: 07b6bcd62ee3
Revises: cb6b648a2a9b
Create Date: 2026-07-08 15:54:17.599497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b6bcd62ee3'
down_revision: Union[str, Sequence[str], None] = 'cb6b648a2a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'], source_schema='platform', referent_schema='platform', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], source_schema='platform', referent_schema='platform', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', 'roles', ['role_id'], ['id'], source_schema='platform', referent_schema='platform', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_roles_role_id_roles'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_role_id_roles'), 'user_roles', 'roles', ['role_id'], ['id'], source_schema='platform', referent_schema='platform', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], source_schema='platform', referent_schema='platform', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', schema='platform', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_roles_role_id_roles'), 'user_roles', schema='platform', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_role_id_roles'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', schema='platform', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', schema='platform', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', schema='platform', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
