"""add hospital schema: categories, suppliers, medicines

Revision ID: 4ec451364d80
Revises: 07b6bcd62ee3
Create Date: 2026-07-08 18:38:49.482844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec451364d80'
down_revision: Union[str, Sequence[str], None] = '07b6bcd62ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS hospital")
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    schema='hospital'
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    schema='hospital'
    )
    op.create_table('medicines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['hospital.categories.id'], name=op.f('fk_medicines_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['hospital.suppliers.id'], name=op.f('fk_medicines_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicines')),
    schema='hospital'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicines', schema='hospital')
    op.drop_table('suppliers', schema='hospital')
    op.drop_table('categories', schema='hospital')
    op.execute("DROP SCHEMA IF EXISTS hospital")
    # ### end Alembic commands ###
