"""add hospital.stocks table

Revision ID: d767e4f241bf
Revises: 4ec451364d80
Create Date: 2026-07-10 18:37:57.071007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd767e4f241bf'
down_revision: Union[str, Sequence[str], None] = '4ec451364d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_stocks_quantity_non_negative')),
    sa.ForeignKeyConstraint(['medicine_id'], ['hospital.medicines.id'], name=op.f('fk_stocks_medicine_id_medicines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    schema='hospital'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks', schema='hospital')
    # ### end Alembic commands ###
